Vagrant.configure("2") do |config|
 
  config.vm.box = "trsenna/gozma12/wp"
 
  config.vm.hostname = "parent2child-blueprints"
  config.vm.network "private_network", ip: "192.168.27.12"

  config.vm.synced_folder "..", "/vagrant"
  config.vm.synced_folder "../themes/genesis21", "/var/www/www.192.168.27.12.xip.io/public_html/wp-content/themes/genesis21"
  config.vm.synced_folder "../themes/kuorinka34", "/var/www/www.192.168.27.12.xip.io/public_html/wp-content/themes/kuorinka34"
  config.vm.synced_folder "../themes/saga49", "/var/www/www.192.168.27.12.xip.io/public_html/wp-content/themes/saga49"
  config.vm.synced_folder "../themes/simppeli37", "/var/www/www.192.168.27.12.xip.io/public_html/wp-content/themes/simppeli37"
  config.vm.synced_folder "../themes/stargazer12", "/var/www/www.192.168.27.12.xip.io/public_html/wp-content/themes/stargazer12"
  config.vm.synced_folder "../themes/twenty15", "/var/www/www.192.168.27.12.xip.io/public_html/wp-content/themes/twenty15"
 
  # Gozma12 Provision
 
  #config.vm.provision "shell", path: "https://raw.githubusercontent.com/trsenna/gozma12/master/cli/core.sh"
  #config.vm.provision "shell", path: "https://raw.githubusercontent.com/trsenna/gozma12/master/cli/lamp.sh"
  #config.vm.provision "shell", path: "https://raw.githubusercontent.com/trsenna/gozma12/master/cli/lapp.sh"
 
  # Local Provision
 
  #config.vm.provision "shell", path: "cli/provision.sh"
 
  # Gozma12 Cookbook Provision
 
  #config.vm.provision "shell", path: "https://raw.githubusercontent.com/trsenna/gozma12-cookbook/master/book/recipes/php5DEV-env.sh"
  #config.vm.provision "shell", path: "https://raw.githubusercontent.com/trsenna/gozma12-cookbook/master/book/recipes/wpDEV-env.sh"
 
end
